version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: backend_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    image: jsquardo/rails-backend:v1
    network_mode: host
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: jsquardo/vite-frontend:v1
    network_mode: host
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm run dev"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5002:5002"
    depends_on:
      - backend
volumes:
  postgres-data: {}
  node_modules: {}
